export enum AtomKeyEnum {
  // atom
  TODO_LIST_ATOM = 'TODO_LIST_ATOM',

  // selector
  NOT_DONE_TODO_LIST_ATOM_SELECTOR = 'NOT_DONE_TODO_LIST_ATOM_SELECTOR',
  DONE_TODO_LIST_ATOM_SELECTOR = 'DONE_TODO_LIST_ATOM_SELECTOR',
  CUR_TODO_LIST_ATOM_SELECTOR = 'CUR_TODO_LIST_ATOM_SELECTOR',
  CUR_ACTIVE_CATEGORY_DETAIL_SELECTOR = 'CUR_ACTIVE_CATEGORY_DETAIL_SELECTOR',
}
